apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-packageinstall-setup"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-packageinstall-setup"
  name: tanzu-tap-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: harbor.h2o-2-1249.h2o.vmware.com/tap/tap-packages:1.3.0
      secretRef: 
        name: tap-registry
        namespace: tap-install