apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tanzu-postgres-operator
  namespace: postgres-operator
spec:
  serviceAccountName: postgres-operator-install-sa
  fetch:
  - helmChart:
      name: postgres-operator
      version: "v1.8.0"
      repository:
        url: oci://harbor.h2o-2-1249.h2o.vmware.com/charts
        secretRef:
          name: tap-registry
  template:
  - helmTemplate:
      valuesFrom:
      - secretRef:
          name: postgres-operator-values

  deploy:
  - kapp: {}